---
# defaults file for mahout
mahout_url: http://apache.claz.org/mahout/0.12.0/apache-mahout-distribution-0.12.0.tar.gz
mahout_archive_name: apache-mahout-distribution-0.12.0.tar.gz
mahout_version: 0.12.0
mahout_user: ubuntu
mahout_home: /opt/mahout
